name: munuuly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.11
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4  # Add this line

flutter:
  uses-material-design: true
  
  assets:
    - assets/1.jpg
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/1.jpg"
  remove_alpha_android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/1.jpg"